---
name: Gradle

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    strategy:
      matrix:
        java: [1.8]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      gradle_version: 5.2.1 # set to empty to build with most recent version of gradle
      gradle_commands: build # default is build
    steps:
      - uses: actions/checkout@v2
      - name: Build Executable
        if: startsWith(matrix.os, 'windows')
        run: |
          nuget install WiX
          echo "PATH=$PWD\WiX.3.11.2\tools;"$PATH
          ls $PWD\WiX.3.11.2\tools
          export $PATH
