---
name: Gradle

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    strategy:
      matrix:
        java: [1.8]
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      gradle_version: 5.2.1 # set to empty to build with most recent version of gradle
      gradle_commands: build # default is build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Wrap with specified version
        run: gradle wrapper --gradle-version=${{ env.gradle_version }}
        if: ${{ env.gradle_version != '' }}
      - name: Wrap without version
        run: gradle wrapper
        if: ${{ env.gradle_version == '' }}
      #- name: Run commands
      #  run: ./gradlew ${{ env.gradle_commands }}
      - name: Build Executable
        if: startsWith(matrix.os, 'windows')
        run: |
          choco uninstall innosetup
          choco install innosetup --version=5.6.1
          nuget install WiX
          ./gradlew packageApplicationExe
          ./gradlew packageApplicationMsi
      - name: Build dm
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install jenv
          brew cask install zulu8
          ls -la /Library/Java/JavaVirtualMachines
          jenv add /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home

          jenv global zulu-8.jdk
          java -version
          ./gradlew packageApplicationDmg
