---
name: Gradle

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    strategy:
      matrix:
        java: [1.8]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      gradle_version: 5.2.1 # set to empty to build with most recent version of gradle
      gradle_commands: build # default is build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Wrap with specified version
        run: gradle wrapper --gradle-version=${{ env.gradle_version }}
        if: ${{ env.gradle_version != '' }}
      - name: Wrap without version
        run: gradle wrapper
        if: ${{ env.gradle_version == '' }}
      - name: Run commands
        run: ./gradlew ${{ env.gradle_commands }}
      - name: Build Executable
        if: startsWith(matrix.os, 'windows')
        run: |
          choco install jdk8
          choco install innosetup --version=5.6.1
          export PATH="/c/Program Files/Java/jdk1.8.0_211:/c/ProgramData/chocolatey/lib/gradle/tools:$PATH"
          export PATH="/c/Program Files (x86)/Inno Setup 5:$PATH"
          export JAVA_HOME="/c/Program Files/Java/jdk1.8.0_211"
          export GRADLE_OPTS="-Dorg.gradle.daemon=false"
          choco install nuget.commandline
          DIR=$PWD
          cd "C:\Program Files (x86)"
          nuget install WiX
          export PATH="/c/Program Files (x86)/WiX.3.11.2/tools:$PATH"
          cd $DIR
          ./gradlew packageApplicationExe
